'use client';
import { useMemo, useState } from 'react';
import { Bell, Building2, CircleDollarSign, CircleUserRound, Headphones, Home, Landmark, MapPin, PlayCircle, PlusCircle, WalletCards } from 'lucide-react';
import type { Balance, PropertyListing } from '@prime/contracts';

type Tab='home'|'apartments'|'finance'|'profile';
const money=(value:number)=>new Intl.NumberFormat('uz-UZ').format(value);
const navItems = [[Home,'home','Home'],[Building2,'apartments','Kvartiralar'],[CircleDollarSign,'finance','Finance'],[CircleUserRound,'profile','Profil']] as const;
const quickItems = [[PlusCircle,'Investitsiya kiritish'],[PlayCircle,'Video darslar'],[Headphones,'Aloqa'],[WalletCards,'Pul yechish']] as const;
export function WebApp({balances,properties}:{balances:Balance[];properties:PropertyListing[];banners:unknown[];videos:unknown[]}){
 const [tab,setTab]=useState<Tab>('home'); const [entries,setEntries]=useState([{type:'income',label:'Maosh',amount:15000000},{type:'expense',label:'Uy xarajati',amount:3200000}]);
 const total=useMemo(()=>entries.reduce((sum,item)=>sum+(item.type==='income'?item.amount:-item.amount),0),[entries]);
 return <div className="webapp"><header className="top"><div className="logo"><span className="logo-mark"><i/><i/><i/></span><span><b>PRIME</b><small>CAPITAL</small></span></div><button aria-label="Bildirishnomalar"><Bell/><em/></button></header><main>
   {tab==='home'?<HomeScreen balances={balances} properties={properties}/>:null}{tab==='apartments'?<ApartmentsScreen properties={properties}/>:null}{tab==='finance'?<FinanceScreen total={total} entries={entries} add={()=>setEntries(current=>[{type:'expense',label:'Yangi xarajat',amount:250000},...current])}/>:null}{tab==='profile'?<ProfileScreen balances={balances}/>:null}
  </main><nav className="bottom-nav">{navItems.map(([Icon,id,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}><Icon/><span>{label}</span></button>)}</nav></div>
}
function HomeScreen({balances,properties}:{balances:Balance[];properties:PropertyListing[]}){return <>
 <section className="hero"><img src="/residence.png" alt="Prime Capital zamonaviy turar joy majmuasi"/><div><h1>Prime joylarda<br/>kelajagingizni yarating</h1><p>Ishonchli investitsiya, barqaror daromad.</p><button>Loyihalarni ko‘rish <span>→</span></button></div></section>
 <section className="balances">{balances.slice(0,2).map((balance,index)=><article key={balance.id}><div className={`account-icon ${index?'cyan':''}`}>{index?<Landmark/>:<Building2/>}</div><div><h2>{balance.name}</h2><span>Hisob raqami</span></div><strong>{money(balance.amount)} <small>so‘m</small></strong><p>Oylik o‘zgarish <b className={balance.monthlyChange<0?'negative':''}>{balance.monthlyChange>0?'+':''}{balance.monthlyChange}% {balance.monthlyChange>0?'↗':'↘'}</b></p></article>)}</section>
 <section className="quick">{quickItems.map(([Icon,label])=><button key={label}><span><Icon/></span>{label}</button>)}</section><Chart/>
 <section className="property-section"><div className="section-title"><h2>Yangi novostroykalar</h2><button>Barchasini ko‘rish →</button></div><div className="property-rail">{properties.slice(0,3).map((item)=><article key={item.id}><div className="property-image"><img src="/residence.png" alt=""/><b>Yangi</b></div><h3>{item.title}</h3><p><MapPin/> {item.location}</p><strong>{money(item.price)} so‘m / m²</strong></article>)}</div></section></>}
function Chart(){return <section className="chart-card"><div className="section-title"><h2>Daromad dinamikasi</h2><select aria-label="Davr"><option>6 oy</option><option>1 yil</option></select></div><div className="chart-legend"><i/> PHP Invest <i/> Prime Capital</div><svg viewBox="0 0 700 250" role="img" aria-label="Daromad dinamikasi"><g className="lines"><line x1="30" y1="45" x2="680" y2="45"/><line x1="30" y1="105" x2="680" y2="105"/><line x1="30" y1="165" x2="680" y2="165"/><line x1="30" y1="225" x2="680" y2="225"/></g><polyline className="turquoise" points="30,120 150,100 270,85 390,95 510,70 680,42"/><polyline className="blue" points="30,190 150,178 270,165 390,140 510,110 680,75"/></svg></section>}
function ApartmentsScreen({properties}:{properties:PropertyListing[]}){return <section className="page"><h1>Kvartiralar</h1><p>Yangi novostroyka va sotiladigan uylar</p><div className="apartment-list">{properties.map(item=><article key={item.id}><img src="/residence.png" alt=""/><div><span>{item.type==='new-build'?'Novostroyka':'Ikkilamchi'}</span><h2>{item.title}</h2><p><MapPin/> {item.location}</p><strong>{money(item.price)} so‘m</strong></div></article>)}</div></section>}
function FinanceScreen({total,entries,add}:{total:number;entries:{type:string;label:string;amount:number}[];add:()=>void}){return <section className="page finance-page"><h1>Finance tracker</h1><p>Kirim va chiqimlaringizni nazorat qiling</p><div className="finance-total"><span>Joriy qoldiq</span><strong>{money(total)} so‘m</strong><button onClick={add}>+ Xarajat qo‘shish</button></div>{entries.map((item,index)=><div className="entry" key={index}><i className={item.type}/><div><b>{item.label}</b><span>{item.type==='income'?'Kirim':'Chiqim'}</span></div><strong className={item.type}>{item.type==='income'?'+':'-'}{money(item.amount)}</strong></div>)}</section>}
function ProfileScreen({balances}:{balances:Balance[]}){return <section className="page profile-page"><div className="profile-head"><CircleUserRound/><div><h1>Azizbek Salimov</h1><p>azizbek@prime.uz</p></div></div>{['Ma’lumotlarim','Support','Aktivlarim','PHP Invest balansim','Prime Capital balansim','Video darslar'].map(label=><button key={label}>{label}<span>›</span></button>)}<button className="logout">Chiqish</button><small>Umumiy balans: {money(balances.reduce((s,b)=>s+b.amount,0))} so‘m</small></section>}
